apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: glpiweb
  template:
    metadata:
      labels:
        app: glpiweb
    spec:
      containers:
      - name: glpiweb
        image: inerente/glpi-suse:v1
        resources:
          limits:
            memory: "3072Mi"
            cpu: "2000m"
        ports:
          - containerPort: 80
        env:
          - name: MARIADB_PORT
            value: "3306"
          - name: DB_HOST
            value: "mariadb-service"

---

apiVersion: v1 
kind: Service
metadata:
  name: glpi-service
spec:
  selector:
    app: glpiweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
    
